import uuid
from django.db import models


# BASE MODEL

class BaseModel(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True



# STUDENT ANALYTICS PROFILE

class StudentAnalyticsProfile(BaseModel):
    """
    Stores computed analytics for each student.
    Updated every time analytics are run.
    """

    student = models.OneToOneField(
        "students.StudentProfile",
        on_delete=models.CASCADE,
        related_name="analytics_profile"
    )

    average_percentage = models.FloatField(default=0.0)
    gpa = models.FloatField(default=0.0)
    attendance_percentage = models.FloatField(default=0.0)

    total_subjects = models.IntegerField(default=0)
    total_failed_subjects = models.IntegerField(default=0)
    weak_subjects_count = models.IntegerField(default=0)

    # Composite score computed by ML pipeline
    performance_score = models.FloatField(default=0.0)

    risk_level = models.CharField(
        max_length=20,
        choices=[
            ("low", "Low"),
            ("medium", "Medium"),
            ("high", "High"),
        ],
        default="low"
    )

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-performance_score"]

    def __str__(self):
        return f"Analytics: {self.student}"



# ML FEATURE STORAGE

class StudentFeature(BaseModel):
    """
    Stores individual ML feature values per student.
    e.g. avg_marks, attendance_rate, failed_count, etc.
    """

    analytics_profile = models.ForeignKey(
        StudentAnalyticsProfile,
        on_delete=models.CASCADE,
        related_name="features"
    )

    feature_name = models.CharField(max_length=100)
    value = models.FloatField(default=0.0)

    class Meta:
        unique_together = ("analytics_profile", "feature_name")

    def __str__(self):
        return f"{self.analytics_profile.student} | {self.feature_name}: {self.value}"



# AI RECOMMENDATION

class AIRecommendation(BaseModel):
    """
    Stores AI-generated recommendations for a student.
    Generated by Content-Based Filtering + Scikit-learn pipeline.
    """

    analytics_profile = models.ForeignKey(
        StudentAnalyticsProfile,
        on_delete=models.CASCADE,
        related_name="recommendations"
    )

    title = models.CharField(max_length=255)
    message = models.TextField()

    # Confidence score from ML model (0.0 to 1.0)
    confidence = models.FloatField(default=0.0)

    algorithm = models.CharField(
        max_length=100,
        default="Content-Based + Scikit-learn"
    )

    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ["-confidence", "-created_at"]

    def __str__(self):
        return f"{self.analytics_profile.student} | {self.title}"
