# Generated by Django 6.0.4 on 2026-05-21 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
