# Generated by Django 6.0.4 on 2026-06-08 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_options'),
        ('students', '0003_alter_studentprofile_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='permanent_adress',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='temprory_adress',
            new_name='temporary_address',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['status'], name='student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['section', 'status'], name='student_section_status_idx'),
        ),
    ]
