# Generated by Django 6.0.4 on 2026-05-23 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_classroutine_room_subject_description_and_more'),
        ('students', '0003_alter_studentprofile_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('result', 'Result'), ('transcript', 'Transcript'), ('class_report', 'Class Report')], max_length=50)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('updated', 'Updated')], max_length=20)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_full_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pass', models.BooleanField(default=True)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.examterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-percentage'],
                'unique_together': {('student', 'exam_term')},
            },
        ),
        migrations.CreateModel(
            name='ClassResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('highest_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lowest_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examterm')),
            ],
            options={
                'unique_together': {('academic_year', 'class_obj', 'exam_term')},
            },
        ),
        migrations.CreateModel(
            name='StudentTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('is_promoted', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theory_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('practical_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('is_pass', models.BooleanField(default=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='reporting_system.studentresult')),
            ],
            options={
                'unique_together': {('student_result', 'class_subject')},
            },
        ),
    ]
