# Generated by Django 6.0.4 on 2026-05-23 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0003_alter_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('term_type', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term'), ('final', 'Final Exam')], db_index=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='academics.academicyear')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theory_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('practical_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='academics.classsubject')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.examterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='examterm',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_exam_term_per_year'),
        ),
        migrations.AddConstraint(
            model_name='studentmark',
            constraint=models.UniqueConstraint(fields=('student', 'exam_term', 'class_subject'), name='unique_student_subject_mark'),
        ),
    ]
