# Generated by Django 6.0.4 on 2026-06-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classroutine_room_subject_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['id'], 'verbose_name_plural': 'Classes'},
        ),
    ]
